- name: Install Junos OS
  hosts: junos_all
  connection: ansible.netcommon.netconf
  gather_facts: no

  vars:
    img_dir: "{{ playbook_dir }}/../../img/junos/ex2200"
    upgrade_package: "{{ img_dir }}/{{ os_img }}"
    log_dir: "{{ playbook_dir }}/../logs"
    netconf_port: 22
    wait_time: 3600

  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      connection: ansible.netcommon.netconf
      junipernetworks.junos.junos_package:
        provider:
          host: "{{ inventory_hostname }}"
        src: "{{ upgrade_package }}"
        reboot: True
        validate: True
      register: response
      notify:
        - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not response.check_mode
