---
- name: Update hosts
  ansible.builtin.import_playbook: plays/dist-upgrade.yml
  tags:
    - never
    - task::upgrade

- name: Provisioning playbook
  ansible.builtin.import_playbook: provision.yml

- name: Configuration playbook
  ansible.builtin.import_playbook: configure.yml

# code: language=ansible
