---
# playbook to configure (newly) provisioned systems

- name: Configure nas
  ansible.builtin.import_playbook: machines/nas/main.yml
  tags:
    - "configure::nas"
    - "configure::all"
    - "never"

- name: Configure www
  ansible.builtin.import_playbook: machines/www/main.yml
  tags:
    - "configure::www"
    - "configure::all"
    - "never"

# name: Configure db
# ansible.builtin.import_playbook: machines/db/main.yml
# tags:
#   - "configure::db"
#   - "configure::all"
#   - "never"

# code: language=ansible
# vim: tw=120
