# SPDX-FileCopyrightText: 2020-Present j. e.j. sahala <git@ejs.sh>
#
# SPDX-License-Identifier: MPL-2.0

---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.network
  - name: linode.cloud
