---
sshd_settings:
  - { regexp: "^PermitRootLogin yes", line: "PermitRootLogin no" }
  - { regexp: "^UseDNS.*", line: "UseDNS no" }
  - {
      regexp: "^#PasswordAuthentication yes",
      line: "PasswordAuthentication no",
    }
