---
#
- name: Set hostname to "{{ host_name }}"
  ansible.builtin.hostname:
    name: "{{ host_name |default('INEEDANAME') }}"

- name: Set timezone to "{{ system_timezone }}"
  community.general.timezone:
    name: "{{ system_timezone |default('Etc/UTC') }}"

- name: Install prerequisites
