---
- hosts: www
  become: yes
  gather_facts: no

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - min

  roles:
    - role: builder-base
    - role: ufw
    # - role: caddy
