---
inventory:
  plugin: YAMLInventory
  options:
    host_file: "config/hosts.yml"
    group_file: "config/groups.yml"
    defaults_file: "config/defaults.yml"

runner:
  plugin: threaded
  options:
    num_workers: 10

logging:
  log_file: "logs/nornir.log"
