---
- hosts: nas
  become: true

  vars_files:
    - vars.yml

  roles:
    ## required
    - role: builder-base
    # - role: zfs
    - role: ufw
    # TODO WIP - role: docker

    ## services
    - role: traefik
    # TODO WIP - role: bind

    #- role: omada
    #- role: gitea
