---
- hosts: nas
  become: true

  vars_files:
    - vars.yml

  roles:
    ## required
    - role: builder-base
    - role: ufw
    - role: k3s

    ## services
    # - role: traefik
    # TODO WIP - role: bind

    #- role: omada
    #- role: gitea
