galaxy_info:
  author: ejsdotsh
  description: Global handlers.
  company: ejsdotsh

  license: Mozilla-2.0

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - handlers
    - system
    - apt

dependencies: []
