# SPDX-FileCopyrightText: 2020-Present j. e.j. sahala <git@ejs.sh>
#
# SPDX-License-Identifier: MPL-2.0

---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
