---
- name: Include global handlers
  ansible.builtin.include_role:
    name: global_handlers

- name: Start Gitea
  block:
    - name: Create Gitea Directories
      ansible.builtin.file:
        path: "{{ gitea_data_directory }}/{{ item }}"
        owner: "{{ gitea_uid }}"
        group: "{{ gitea_uid }}"
        mode: 0770
        state: directory
        recurse: yes
      with_items:
        - "gitea"
        - "postgres"

    - name: Create gitea network
      community.docker.docker_network:
        name: "{{ gitea_network_name }}"

    - name: Create postgres container for Gitea
      community.docker.docker_container:
        name: "{{ gitea_postgres_container_name }}"
        image: "{{ gitea_postgres_image_name }}:{{ gitea_postgres_image_version }}"
        pull: true
        networks:
          - name: "{{ gitea_network_name }}"
        network_mode: "{{ gitea_network_name }}"
        volumes:
          - "{{ gitea_data_directory }}/postgres:/var/lib/postgres:rw"
        env:
          POSTGRES_USER: "gitea"
          POSTGRES_PASSWORD: "{{ vault.gitea_dbpass }}"
          POSTGRES_DB: "gitea"
        restart_policy: unless-stopped
        memory: "{{ gitea_postgres_memory }}"

    - name: Create Gitea container
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        image: "{{ gitea_image_name }}:{{ gitea_image_version }}"
        pull: true
        networks:
          - name: "{{ gitea_network_name }}"
        network_mode: "{{ gitea_network_name }}"
        volumes:
          - "{{ gitea_data_directory }}/gitea:/data:rw"
        ports:
          - "{{ gitea_port_http }}:3000"
          - "{{ gitea_port_ssh }}:22"
        env:
          DB_TYPE: "postgres"
          DB_HOST: "{{ gitea_postgres_container_name }}:5432"
          DB_NAME: "gitea"
          DB_USER: "gitea"
          DB_PASSWD: "{{ vault.gitea_dbpass }}"
          RUN_MODE: "prod"
          SSH_DOMAIN: "{{ gitea_hostname }}"
          SSH_PORT: "22"
          # ROOT_URL: "http://{{ gitea_hostname }}.{{ domain_name }}:{{ gitea_port_http }}/"
          ROOT_URL: "http://{{ gitea_hostname }}:{{ gitea_port_http }}/"
          USER_UID: "{{ gitea_uid }}"
          USER_GID: "{{ gitea_uid }}"
        restart_policy: unless-stopped
        memory: "{{ gitea_memory }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.gitea.rule: "Host(`{{ gitea_hostname }}.{{ domain_name }}`)"
          traefik.http.routers.gitea.tls.certresolver: "lego"
          traefik.http.routers.gitea.tls.domains[0].main: "{{ domain_name }}"
          traefik.http.routers.gitea.tls.domains[0].sans: "*.{{ domain_name }}"
          traefik.http.services.gitea.loadbalancer.server.port: "3000"
  when: gitea_enabled is true

- name: Stop Gitea
  block:
    - name: Stop Gitea
      community.docker.docker_container:
        name: "{{ gitea_container_name }}"
        state: absent

    - name: Stop Gitea postgres
      community.docker.docker_container:
        name: "{{ gitea_postgres_container_name }}"
        state: absent
  when: gitea_enabled is false
