galaxy_info:
  author: ejsdotsh
  description: A basic UFW management role.
  company: ejsdotsh

  license: Apache-2.0

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system
    - firewall
    - ufw
    - security

dependencies:
  - role: global_handlers